"""Initial migration

Revision ID: 0e12cb47dd82
Revises: 
Create Date: 2024-11-22 11:22:09.219497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e12cb47dd82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('athlete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint("gender IN ('Homme', 'Femme', 'Autre')", name='valid_gender'),
    sa.ForeignKeyConstraint(['team_name'], ['team.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('source_excel', sa.JSON(), nullable=False),
    sa.Column('source_vo2', sa.JSON(), nullable=False),
    sa.Column('computed_dataframe', sa.JSON(), nullable=True),
    sa.Column('plateau_dataframe', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('pdf_report', sa.BLOB(), nullable=True),
    sa.Column('pdf_report_short', sa.BLOB(), nullable=True),
    sa.Column('graphics', sa.BLOB(), nullable=True),
    sa.Column('protocol', sa.BLOB(), nullable=True),
    sa.Column('plateau_study', sa.BLOB(), nullable=True),
    sa.Column('time_under_trend_plateau', sa.Integer(), nullable=True),
    sa.Column('time_above_trend_plateau', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=True),
    sa.Column('area_under_trend_plateau', sa.Integer(), nullable=True),
    sa.Column('area_above_trend_plateau', sa.Integer(), nullable=True),
    sa.Column('total_area_plateau', sa.Integer(), nullable=True),
    sa.Column('start_speed_plateau', sa.Float(), nullable=True),
    sa.Column('shape_plateau', sa.String(), nullable=True),
    sa.Column('slope_s1', sa.Float(), nullable=True),
    sa.Column('speed_s1', sa.Float(), nullable=True),
    sa.Column('vo2_s1', sa.Float(), nullable=True),
    sa.Column('vo2_kg_s1', sa.Float(), nullable=True),
    sa.Column('vo2_ratio_s1', sa.Float(), nullable=True),
    sa.Column('ve_s1', sa.Float(), nullable=True),
    sa.Column('hr_s1', sa.Integer(), nullable=True),
    sa.Column('hr_ratio_s1', sa.Float(), nullable=True),
    sa.Column('watt_s1', sa.Float(), nullable=True),
    sa.Column('watt_kg_s1', sa.Float(), nullable=True),
    sa.Column('de_s1', sa.Float(), nullable=True),
    sa.Column('glu_s1', sa.Float(), nullable=True),
    sa.Column('lip_s1', sa.Float(), nullable=True),
    sa.Column('lactate_s1', sa.Float(), nullable=True),
    sa.Column('slope_s2', sa.Float(), nullable=True),
    sa.Column('speed_s2', sa.Float(), nullable=True),
    sa.Column('vo2_s2', sa.Float(), nullable=True),
    sa.Column('vo2_kg_s2', sa.Float(), nullable=True),
    sa.Column('vo2_ratio_s2', sa.Float(), nullable=True),
    sa.Column('ve_s2', sa.Float(), nullable=True),
    sa.Column('hr_s2', sa.Integer(), nullable=True),
    sa.Column('hr_ratio_s2', sa.Float(), nullable=True),
    sa.Column('watt_s2', sa.Float(), nullable=True),
    sa.Column('watt_kg_s2', sa.Float(), nullable=True),
    sa.Column('de_s2', sa.Float(), nullable=True),
    sa.Column('glu_s2', sa.Float(), nullable=True),
    sa.Column('lip_s2', sa.Float(), nullable=True),
    sa.Column('lactate_s2', sa.Float(), nullable=True),
    sa.Column('tps_max', sa.Integer(), nullable=True),
    sa.Column('slope_max', sa.Float(), nullable=True),
    sa.Column('speed_max', sa.Float(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('vo2_kg_max', sa.Float(), nullable=True),
    sa.Column('vo2_ratio_max', sa.Float(), nullable=True),
    sa.Column('ve_max', sa.Float(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('hr_ratio_max', sa.Float(), nullable=True),
    sa.Column('watt_max', sa.Float(), nullable=True),
    sa.Column('watt_kg_max', sa.Float(), nullable=True),
    sa.Column('de_max', sa.Float(), nullable=True),
    sa.Column('glu_max', sa.Float(), nullable=True),
    sa.Column('lip_max', sa.Float(), nullable=True),
    sa.Column('lactate_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athlete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('athlete')
    op.drop_table('team')
    # ### end Alembic commands ###
